// This file has been autogenerated from a class added in the UI designer.

using System;

using UIKit;

namespace Kudo.iOS.ModelViews
{
	public partial class TabsMenuController : UITabBarController
    {

        public TabsMenuController (IntPtr handle) : base (handle)
        {

        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}
