// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Kudo.iOS.Views
{
	public partial class GameCell : UICollectionViewCell
	{
		public GameCell (IntPtr handle) : base (handle)
		{
		}
	}
}
